### ISSUE TITLE
There is no python3 support

### ISSUE THREAD

**Issue by ignisphaseone** [Timusan/wtforms-dynamic-fields#1]
Hey Timusan,

I noticed that there's no python3 "support"! I'm new to the whole python packaging thing, but I downloaded it via pip and I just ran 2to3 on it. I'm going to take it for a spin, but if there's any 'official' way to add the python3 support, that would be awesome.

I'll also see if there's any bugs that come up from doing this.

**Comment by Timusan** [comment]
Hi Eric

Thanks for trying the module, and as stated in the short documentation: the module is currently in a "personal itch went open source" state. With the valuable input from other programmers (like you), I will be able to make it into something more stable and generic.

I will look into adding Python 3 support today and look into setting up Tox for testing builds over various interpreter versions.

**Comment by Timusan** [comment]
I just added the necessary fixes to make the code support both recent Python 2 versions (2.6, 2.7) and Python 3 (3.2, 3.3, 3.4). For most of these interpreters I added Tox integrated testing support.
